language: php
dist: bionic

matrix:
  include:
  - php: '7.1'
    env: SWOOLE_VERSION="v4.5.3"
  - php: '7.2'
    env: SWOOLE_VERSION="v4.5.3"
  - php: '7.3'
    env: SWOOLE_VERSION="v4.5.3"
  - php: '7.4'
    env: SWOOLE_VERSION="v4.5.3"
  - php: '7.1'
    env: SWOOLE_VERSION="v4.4.19"
  - php: '7.2'
    env: SWOOLE_VERSION="v4.4.19"
  - php: '7.3'
    env: SWOOLE_VERSION="v4.4.19"
  - php: '7.4'
    env: SWOOLE_VERSION="v4.4.19"
  # allow_failures:
  # - env: SWOOLE_VERSION="v4.5.3-beta"

services:
  - redis
  - mysql

addons:
  apt:
    packages:
    - unzip
    - chromium-browser

install:
  - $CHROME_HEADLESS_PATH --version
  - dd if=/dev/zero of=swap bs=1024 count=2048000 && chmod 600 swap && sudo mkswap swap && sudo swapon swap
  - if [[ $INSTALL_REDIS_EXT == true ]]; then
      wget https://github.com/phpredis/phpredis/archive/develop.zip;
      unzip develop.zip;
      cd phpredis-develop;
      phpize;
      ./configure;
      make && make install;
      cd ../;
    fi
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && php --ri redis
  - wget https://github.com/swoole/swoole-src/archive/$SWOOLE_VERSION.tar.gz -O swoole.tar.gz && mkdir -p swoole && tar -xf swoole.tar.gz -C swoole --strip-components=1 && rm swoole.tar.gz && cd swoole && phpize && ./configure --enable-openssl --enable-http2 --enable-mysqlnd && make -j && make install && cd - && echo "extension = swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && php --ri swoole

before_script:
  - if [[ $DISABLE_XDEBUG != false ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - if [[ $DOWNLOAD_PHPUNIT != "" ]]; then
      curl -sSfL -o ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-$DOWNLOAD_PHPUNIT.phar && php ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit --version && export TEST_PHPUNIT_PATH=~/.phpenv/versions/$(phpenv version-name)/bin/phpunit;
    fi
  - composer -V && composer update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_yurun_crawler_test;' && vendor/bin/imi generate/table -appNamespace "Yurun\Crawler\Test"

script:
  - ./tests/run

env:
  global:
    - MYSQL_SERVER_USERNAME: root
    - MYSQL_SERVER_PASSWORD:
    - CHROME_HEADLESS_PATH: chromium-browser